import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TanstackProvider from "@/components//TanStackProvider/TanstackProvider";

import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Note Hub",
  description: "Generated by GoIt & Valeriia Makushchenko",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanstackProvider>
          <Header />
          <main className="main">
            <div className="container">{children}</div>
          </main>

          <Footer />
        </TanstackProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
